---
- name: DD task block
  block:
    # Ansible fact: ansible_devices

    - name: DD disks including
      when: "{{ dd_list }} == include"

    - name: DD disks excluding
      when: "{{ dd_list }} == exclude"
  when: dd_run
